### ISSUE TITLE
Use of the encoding pragma is deprecated

### ISSUE THREAD

**Issue by toddr** [gfx/p5-HTML-FillInForm-Lite#3]
```
$>perl522 -Mblib  t/06encoding_sjis.t
1..4
Use of the encoding pragma is deprecated at t/06encoding_sjis.t line 17.
ok 1 - use HTML::FillInForm::Lite;
ok 2 - Unicode value
ok 3 - Unicode name
ok 4 - Unicode name/value
```

The code uses this statement which is now deprecated in perl 5.22
```perl
use encoding 'Shift_JIS';
```

https://metacpan.org/pod/distribution/perl/pod/perldelta.pod#use-encoding-is-now-lexical

**Comment by toddr** [comment]
I don't have any suggestion other than to remove the test or change the characters to utf-8. Is that possible?

**Comment by gfx** [comment]
:eyes:

**Comment by eserte** [comment]
See also https://github.com/gfx/p5-HTML-FillInForm-Lite/issues/6
