### ISSUE TITLE
Undeclared dependency Test::Requires (1.14)

### ISSUE THREAD

**Issue by eserte** [gfx/p5-HTML-FillInForm-Lite#5]
t/01input.t and t/10compat.t fail if Test::Requires is not installed.

**Comment by gfx** [comment]
😞

**Comment by toddr** [comment]
:( :(

**Comment by toddr** [comment]
pull request #7 fixes this though I think minil will do the magic for you?

**Comment by gfx** [comment]
Fixed in 1.15. Thanks.
